### ISSUE TITLE
Strategy for your new startup

### ISSUE THREAD

**Issue by iakshay** [rishabhp/ama#13]
If you were to develop iOS/Android apps for your new startup (something like instagram, when it launched). 

- What would be your preferred tech stack for both API backend and mobile apps? (Mention - languages/frameworks, database engines and 3rd party services)
- Would you opt for hybrid apps?
- Would you prefer to work alone? or get more people - you don't have funding yet.
- Go into as much detail as you like.

**Comment by rishabhp** [comment]
- Depending upon my target country I'd choose whether to build the Android or iOS version first. It's highly likely that I'd go with Android given I'd target my country first. Tech stack would most probably be Node.js for backend code and probably MongoDB as the DB. I like third party services like Parse and PubNub, so might consider using them too depending upon the requirements. I haven't worked with RethinkDB yet, but that should be a decent DB solution too.
- Not a big fan of hybrid apps, but certain screens inside a native app can be hybrid.
- Would prefer to get more people on board.
