### ISSUE TITLE
Why can't I delete my CSSDeck account?

### ISSUE THREAD

**Issue by HugoGiraudel** [rishabhp/ama#14]

**Comment by rishabhp** [comment]
I didn't expect people wanting to delete accounts hence the feature was never built into the platform (was following an MVPish approach). For more than 2 years I haven't really got the time to integrate any "proper" feature. All the commits made to the codebase are hotfixes or important textual changes.

The ownership of CSSDeck has been transferred to another team who will hopefully take it forward positively. I'll let them know about this request.
