### ISSUE TITLE
android SMS 

### ISSUE THREAD

**Issue by gootgate** [rishabhp/ama#16]
how can i receive sms with specific keyword to my app and then split and show the words separately
example:
the sms:
"keyword john 12 A"
i want to show it as:
name:john
age:12
grade:A

**Comment by rishabhp** [comment]
This might require some explanation which is already done in one of my articles on [Android SMS](http://codetheory.in/android-sms/). Once you receive the SMS you can do some sort of String manipulation/parsing (like using [`split()`](http://www.tutorialspoint.com/java/java_string_split.htm)).
