### ISSUE TITLE
Hello Rishabhp

### ISSUE THREAD

**Issue by yomigits** [rishabhp/ama#18]
Please I will like to know how to add google map as part of the page in the Android Sliding Sidebar you created. Please I expect your reply. Thank you.

**Comment by yomigits** [comment]
Waiting for your reply and if possible let me know if you can support me in developing the whole app. Will pay you.

**Comment by rishabhp** [comment]
Never done Gmaps integration, so don't think I can help in this case. [This](https://developer.android.com/training/maps/index.html) should be of great help!
