### ISSUE TITLE
Backend or Frontend?

### ISSUE THREAD

**Issue by srinivasdamam** [rishabhp/ama#19]
Hey, Hi. I have a question. I just completed my grad this April. I would like be a web developer. I'm confused whether to choose front end or back end. Can you please guide me details about salary, hike, work/life balance in two cases? Yeah, I like front end than back end. I'm also interested in mobile app developed. I'm banging my head against the wall confused with my career. Please guide me. Thank you.

**Comment by rishabhp** [comment]
You want to be a web developer.

Start off with HTML/CSS/JavaScript. You'll learn some frontend that way.

Then learn Node.js which helps you write backend code in JS. You'll learn some backend that way.

Build a "fun" project then. You'll end up applying both frontend and backend knowledge, learning more in the process.

Then you'll be able to decide for yourself. You would later want to play with other programming languages like Ruby, Python, PHP. Don't think about salary, hike and work/life balance at the beginning of your career. They don't matter at this stage. Work hard and you'll get all of that later.

:-)
