### ISSUE TITLE
I heard you feel that people of your age are dumb and naive, is that true?

### ISSUE THREAD

**Issue by hemanth** [rishabhp/ama#2]

**Comment by rishabhp** [comment]
Haha no way! I've met some really smart people who're younger than me, in
conferences and around the web.

On Tue, Jul 14, 2015 at 5:54 PM, hemanth.hm <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rishabhp/ama/issues/2>.
>



-- 
Thanks and Best Regards,
Rishabh
Twitter: @_rishabhp <http://twitter.com/_rishabhp>
Blog: http://codetheory.in
