### ISSUE TITLE
CSS animations and window switching cause CPU to run hot

### ISSUE THREAD

**Issue by jeremykohn** [rishabhp/ama#21]
On web pages with CSS animations, my web browser's CPU usage rises to about 50%-110% and causes the computer's fan to spin much more rapidly.

It happens even with simple animations like these:

cssdeck.com/labs/4gt1nsbb
cssdeck.com/labs/r4dc8dxu

Similarly, when I quickly and repeatedly switch browser windows, the browser's CPU usage rises to about 40%-80%.

(By comparison, the browser only consumes about 10%-30% of CPU during normal use.)

Is this supposed to happen? And if not, how might I fix it?

**Comment by rishabhp** [comment]
The animations are fairly simple and shouldn't consume a lot of your CPU. There might be other processes affecting it. Try a system reboot.
