### ISSUE TITLE
How to get a better job in android app development?

### ISSUE THREAD

**Issue by mohdaquib** [rishabhp/ama#22]
Hi rishabh,
                I am working as an Android app developer at junior level in a company based in New Delhi. Actually, I am only person who handle android development. I have already launched 4 apps on play store. But those apps are not good in design point of view. Actually there is not a particular person for UI design. I find a company where I can work in team environment. I do have one year of experience in android development. How much I would take time to get a better job.

**Comment by rishabhp** [comment]
Build some test apps/projects in Android that contains features that'd cover a lot of the android functionalities (APIs basically). Put that up on Github then and prepare a good looking resume.

Start applying to companies. If you feel like doing freelancing (to earn some money till you get a job) then check out Elance or Freelancer too!

There's a good demand of mobile developers in the Indian startup ecosystem.

Although your question has "better" which might mean that you're looking out for a change. Try connecting to people on linkedin, check out hasjob that has startup jobs listed, attend conferences for networking purposes, etc. Also if you feel like shoot me an email with your resume, will share it with our Mobile and HR team at ZoomCar.

**Comment by mohdaquib** [comment]
Thanks Rishabh for guiding me.

**Comment by vinitthaker** [comment]
You can apply for various startup at angel.co website also. I am working at yourguy.in as an android developer and i got this opportunity via angel.co only. Try it out. It is really a great platform.
