### ISSUE TITLE
Service triggered by user or period

### ISSUE THREAD

**Issue by ook** [rishabhp/ama#25]
I'm looking for the best approach to implement a service that can be triggered manually or every n seconds, depending of the first occurring.
Thanks by advance.

**Comment by rishabhp** [comment]
Implementing a service that is trigger manually is fairly simple, you'll have to read up on [Services](http://codetheory.in/understanding-android-started-bound-services/). Triggering it periodically is something that I have never done but it seems like [Alarms](https://developer.android.com/training/scheduling/alarms.html) will be of great help here.
