### ISSUE TITLE
Pwned scrub m9 

### ISSUE THREAD

**Issue by xxx-billy-xxx** [rishabhp/ama#27]
What is the sqrt(-1),

**Comment by rishabhp** [comment]
Check [this](https://www.google.co.in/search?q=square+root+of+negative+numbers&oq=square+root+of+negative+numbers&aqs=chrome.0.69i59j0l5.3983j0j9&sourceid=chrome&es_sm=91&ie=UTF-8). Also you can try the code in dev tools or some other interactive shell.
