### ISSUE TITLE
How is your experience with zoomcar?

### ISSUE THREAD

**Issue by vinitthaker** [rishabhp/ama#28]
I didnt like the website of zoomcar. But android app was ok ok not that bad. So i think it is still evolving so it will take some time to improve overall UI and efficiency of the entire system.

**Comment by rishabhp** [comment]
Agree with you. We're about to launch a new website design which improves the overall UI/UX by magnitudes. The app will also go through a cool new makeover over the next few months.

Company's initial focus was mostly solving problems which meant spending a lot of time into operations and solving operational problems with technology. There's a lot more focus on design now.
