### ISSUE TITLE
hi ama

### ISSUE THREAD

**Issue by vahidalvandi** [rishabhp/ama#31]
i reed your weblog about gravity in html 5 . 

i need build a web application realtime which get parameters from client and draw its,

for example i have ball and it rotate around circle and i have text box . after change variable change speed ball.

please help me. thnaks

**Comment by rishabhp** [comment]
I'm confused. I think I've written articles on my blog that covers various relevant (to the keywords in your question) concepts. For realtime you can use [Socket.io](http://socket.io/).
