### ISSUE TITLE
What did you have for breakfast?

### ISSUE THREAD

**Issue by sindresorhus** [rishabhp/ama#7]

**Comment by rishabhp** [comment]
[Vermicelli](https://www.google.co.in/search?q=vermicelli&es_sm=91&tbm=isch&imgil=mu6lJ2E-ccAuNM%253A%253BNvlAA1vH2Gr0VM%253Bhttp%25253A%25252F%25252Fhonestcooking.com%25252Fvermicelli-vegetable-upma%25252F&source=iu&pf=m&fir=mu6lJ2E-ccAuNM%253A%252CNvlAA1vH2Gr0VM%252C_&usg=__2oBsrFZq3FXAj8WOGGSwnc3GLmI%3D#imgrc=mu6lJ2E-ccAuNM%3A&usg=__2oBsrFZq3FXAj8WOGGSwnc3GLmI%3D)
