### ISSUE TITLE
What was your primary motivation behind creating CSSDeck?

### ISSUE THREAD

**Issue by nihar108** [rishabhp/ama#9]

**Comment by rishabhp** [comment]
While building web apps back in 2011 I got to learn that using CSS3 gradients and border-radius, cool navigations and buttons could be made. Sometimes I'd code these UI elements myself but other times I'd search for code on the internet and fail. Hence it occurred to me that a repository of cool UI elements would not only help me and my team mates but other people in the community too. So I built the website with lots of items posted by me (most of them were elements taken from the famous twitter bootstrap framework - I sort of decomposed it into its elements on CSSDeck) and later saw other people would also post stuff. Later there was a little pivot (based on feedbacks) where the platform sort of became a playground like the famous JSFiddle but with featured items.

Rest is history.
